name: Release

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:               
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}-${{ github.run_id }}
          tag_name: ${{ github.ref_name }}-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-macos:
    needs: create-release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          ./src/main/scripts/ci-download.sh
          brew install autoconf automake libtool
          export PATH="/opt/homebrew/opt/libtool/libexec/gnubin:$PATH"
          ./src/main/scripts/ci-build.sh 2
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: target/
      - name: upload jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/mpfr_java-1.4.jar
          asset_name: mpfr_java-1.4.jar
          asset_content_type: application/binary
      - name: upload jnilib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/mpfr_java-1.4-osx64.jar
          asset_name: mpfr_java-1.4-osx64.jar
          asset_content_type: application/binary

  build-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          ./src/main/scripts/ci-download.sh
          apt update && apt install -y autoconf automake libtool
          ./src/main/scripts/ci-build.sh 2
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: target/
      - name: upload jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/mpfr_java-1.4.jar
          asset_name: mpfr_java-1.4-linux.jar
          asset_content_type: application/binary
      - name: upload native lib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./target/mpfr_java-1.4-linux64.jar
          asset_name: mpfr_java-1.4-linux64.jar
          asset_content_type: application/binary
